### PR TITLE
Scope of the Variable

### PR DESCRIPTION
**Pull request by lucasborin**

### CODE REVIEW

**Review by estevao-schultz-neto-SAP — APPROVED** [review]
I will check/create the documentation.

**Comment by lucasborin** [comment]
Don't declare inline in optional branches
https://github.com/SAP/styleguides/blob/master/clean-abap/CleanABAP.md#dont-declare-inline-in-optional-branches

**Review by estevao-schultz-neto-SAP — APPROVED** [review]

**Review by estevao-schultz-neto-SAP — APPROVED** [review]
Pseudo-Comment is the same?

**Comment by lucasborin** [comment]
Nope, it was changed to "#EC SCOPE_OF_VAR

**Comment by lucasborin** [comment]
We have to change the check description and message before merging it.

**Comment by lucasborin** [comment]
"Variable out of its Scope!"

@estevao-schultz-neto-SAP: How about it?

**Comment by lucasborin** [comment]
Tested in ABAP 7.40 => Ready to release the next version.

**Comment by estevao-schultz-neto-SAP** [comment]
> Check Message => "Variable out of its scope!"
> Documentation => [scope-of-variable.md](https://github.com/SAP/code-pal-for-abap/blob/Scope-of-the-Variable/docs/checks/scope-of-variable.md)
> 
> @estevao-schultz-neto-SAP: How about it?

it's good. I will review the whole documentation this week.

**Review by estevao-schultz-neto-SAP — APPROVED** [review]

**Pull request merged**
