### PR TITLE
Prefer New to Create Object

### PR DESCRIPTION
**Pull request by lucasborin**

### CODE REVIEW

**Comment by lucasborin** [comment]
@estevao-schultz-neto-SAP : Could you please review the `prefer-new-to-create-object.md`?

**Review by estevao-schultz-neto-SAP — CHANGES_REQUESTED** [review]
Only changed the HELP .md file. Small things. The rest is fine.

**Comment by lucasborin** [comment]
@estevao-schultz-neto-SAP : It looks like you have already changed the .md file; It is fine. Could you please approve the pull request?

**Comment by lucasborin** [comment]
we have to implement the example in the demo class.

**Review by estevao-schultz-neto-SAP — APPROVED** [review]

**Pull request merged**
