### PR TITLE
Raising profile message only once

### PR DESCRIPTION
**Pull request by lucasborin**

### CODE REVIEW

**Comment by lucasborin** [comment]
Can we set it as Prio 4 in the ATC (using Code Inspector behind)?

**Comment by lucasborin** [comment]
image

**Comment by lucasborin** [comment]
New Message:
image

**Comment by lucasborin** [comment]
New Message:
image

**Comment by lucasborin** [comment]
@estevao-schultz-neto-SAP I refactored the Profile Feature Notification. Now it runs only once, and the description and message might be easier to understand. Could you please take a look at it?

**Review by estevao-schultz-neto-SAP — APPROVED** [review]

**Comment by estevao-schultz-neto-SAP** [comment]
image

I just found out that the messages are somehow strange now when using a profile  (not showing any parameter). Is it a regression?

**Comment by lucasborin** [comment]
Actually, this is the default message without the parameters. 
You can check the real finding in the details. (same behavior in all the checks).

image

**Pull request merged**
