### PR TITLE
`cut` as default

### PR DESCRIPTION
**Pull request by lucasborin**

### CODE REVIEW

**Comment by lucasborin** [comment]
@estevao-schultz-neto-SAP: Would you mind reviewing the new documentation?

**Comment by lucasborin** [comment]
image

`cut` in the method name should be ignored.

**Review by estevao-schultz-neto-SAP — COMMENTED** [review]
Hello Buddy, I don't think this check should be "enforced" in the sense that someone will need to use the pseudo-comment in case he/she has used a MEANINGFUL name. I think we have a mismatch here. From the text: **_"...In a test class, the code under the test can be represented using a meaningful name, or `cut` as a default..."_** either CUT or a MEANINGFUL name should be accepted. But what is a meaningful name then? Subjective...

**Long story short**: IMHO, this CHECK will mostly be used as a NOTIFICATION in case someone is not using "cut" (and in case the team agreed so -- team decision). 

Moreover, I would change the description so that: _**"...In a test class, the code under the test can be represented using a meaningful name or `cut` as a default. If your team decided to use 'cut', this check can be helpful on identifying deviations.". **_

We talk about it further.

**Review by eugen-guenther-sap — DISMISSED** [review]
looks good to me

**Comment by lucasborin** [comment]
> Hello Buddy, I don't think this check should be "enforced" in the sense that someone will need to use the pseudo-comment in case he/she has used a MEANINGFUL name. I think we have a mismatch here. From the text: **_"...In a test class, the code under the test can be represented using a meaningful name, or `cut` as a default..."_** either CUT or a MEANINGFUL name should be accepted. But what is a meaningful name then? Subjective...
> 
> **Long story short**: IMHO, this CHECK will mostly be used as a NOTIFICATION in case someone is not using "cut" (and in case the team agreed so -- team decision).
> 
> Moreover, I would change the description so that: **_"...In a test class, the code under the test can be represented using a meaningful name or `cut` as a default. If your team decided to use 'cut', this check can be helpful on identifying deviations.". _**
> 
> We talk about it further.

All the checks are NOTIFICATION by default so, as you mentioned, it is up to the team to decide if they want to follow cut as the main default or not. The check will just support these ones. Besides, I will enhance the documentation as you mentioned.

**Comment by bjoern-jueliger-sap** [comment]
Closing this as no longer relevant

**Pull request closed without merging**
