### PR TITLE
Handle functional operand in assert check

### LINKED ISSUE #460: Unit Test Assert does not allow to check method calls for idempotence
> 💡 Code pal for ABAP follows the [Clean ABAP](https://github.com/SAP/styleguides/blob/main/clean-abap/CleanABAP.md). If the issue relates to coding style, please submit it [here](https://github.com/SAP/styleguides/issues). 

**Check Name**
[unit test assert](https://github.com/SAP/code-pal-for-abap/blob/master/docs/checks/unit_test_assert.md)

**Actual Behavior**
If the same method is called twice in actual and expected, e.g. to test that a factory method returns a singleton, 'illegal assert' is raised

**Expected Behavior**
For method calls, dispense with the rule, since idempotence is a meaningful test.

### PR DESCRIPTION
**Pull request by pokrakam**
Closes #460 
Searches for functional operand syntax within the compared strings if they are equal.
Also discovered and fixed bug in parenthesis parsing - `var+2(1)` incorrectly parsed the entire rest of the statement.

Cannot run unit tests due to #461 but I believe they should work.

### CODE REVIEW

**Comment by lucasborin** [comment]
Conflicts fixed.

**Review by lucasborin — CHANGES_REQUESTED** [review]
There are some broken unit tests:

image

Three syntax errors:
image

**Comment by pokrakam** [comment]
I fixed the unit test syntax errors, but have no idea why `ltc_call_static` is failing as I can't run tests :(
I tested my change with code in a report and running ATC. Doing the same with the ltc_call_static passes.

**Comment by lucasborin** [comment]
The broken UT was checking if the Check was raising an issue for act&exp calling a static method with the same parameters. As of now, the Check won't check classes and methods anymore. Therefore, I removed it.

**Review by lucasborin — APPROVED** [review]

**Pull request merged**
