### PR TITLE
2.00.0 - RFC Ready - Major Base Change!

### PR DESCRIPTION
**Pull request by lucasborin**
* Enable RFC 
* Exemption based on TADIR/TRDIR/ENLFDIR gen flag
* Renaming objects
* Less global objects
* Object creation date no longer uses the `VRSD` table
* Option to evaluate new child objects
* Performance optimization

** Migration Required **

⚠️ not supported in ABAP 7.40!

💡 after releasing it, change the `master` branch to `main`

### CODE REVIEW

**Comment by lucasborin** [comment]
Telemetry will flood that database. Should we log findings only? Should we document how to turn it off?

**Comment by lucasborin** [comment]
Performance test:
* 91 objects = ~9.5s = 63% ABAP, 37% DB
* 744 objects = ~162s = 80% ABAP, 20% DB

**Comment by abap-weasel** [comment]
Just found the new branch after tweet from Thomas and noticed the warning not supported in ABAP 7.40. 
Is this just temporary during development of V2 or will V2 also not run in 7.40 after release? (this will block us from using code-pal.... )

**Comment by bjoern-jueliger-sap** [comment]
This will not be finished or merged; for a remote-enabled version of Code Pal, use [our Cloud version](https://github.com/SAP/code-pal-for-abap-cloud)

**Pull request closed without merging**
